### ISSUE TITLE
Is there going to be support of loadable/components ? or we should wait when React.lazy will support ssr?

### ISSUE THREAD

**Issue by AndriiUhryn** [manuelbieh/react-ssr-setup#102]

**Comment by zorgick** [comment]
Hi! I'm subscribed to this repo, and recently I was strugling with the same
problem. There are some caveats in using loadable/components (tldr; their
solution doesn't work with redux state splitting). You can check out my
solution here https://github.com/zorgick/Initial_setup

чт, 23 янв. 2020 г., 18:32 Andrii <notifications@github.com>:

**Comment by manuelbieh** [comment]
You can [use this repo as a template](https://github.com/manuelbieh/react-ssr-setup/generate) and then use whatever loadable/lazy package you like. Although I'm also very impatient already, I'm going to wait until Suspense and React.lazy is officially supported.

**Comment by manuelbieh** [comment]
https://github.com/overlookmotel/react-lazy-ssr
