### ISSUE TITLE
Use https for local dev server

### ISSUE THREAD

**Issue by tusharf5** [manuelbieh/react-ssr-setup#12]
First of all thanks for an amazing repo. 

How can I serve local files in `development` mode with https server? with `webpack-dev-server` you get a `https: true` option but I guess that is not available here?

**Comment by manuelbieh** [comment]
To be honest: i never used https in devmode so I currently have no idea 😉  I will figure it out and add a similar option once that's done.

**Comment by tusharf5** [comment]
I got it to work after the following steps

- Install `pem` for dynamically generating certificates for local runs.
- Create an https server and pass your `app` instance to it.

```javascript

import https from 'https';
import pem from 'pem';

const app = express();

pem.createCertificate({ days: 365, selfSigned: true }, (err, keys) => {
  if (err) {
    throw err;
  }

  https
    .createServer({ key: keys.serviceKey, cert: keys.certificate }, app)
    .listen(8443, () => {
      console.log('App is running: 🌎 https://localhost:8443');
    });
});
```
