### ISSUE TITLE
Serve multiple routes with different components.

### ISSUE THREAD

**Issue by aimeelaplant** [manuelbieh/react-ssr-setup#22]
I looked through the code but can't find an example of serving multiple routes with a 404 if the route isn't found.

I'm assuming adding a new route would be somewhere in `src/server/render.js` here:

```
        <Provider store={req.store}>
            <Router location={req.url} context={{}}>
                <IntlProvider>
                    <App />
                </IntlProvider>
            </Router>
        </Provider>
```

And to serve the client router,  I would have to add the same thing in `src/client/index.js`?

Do you have an example of serving multiple components with routes? The current configuration is a catch all, so it matches any link to the browser.

With react-router, the documentation says to do this for multiple routes:

<Switch>
   <Route path="/something" component={Something} />
</Switch>

But this context switching doesn't work in `src/server/render.js`.

**Comment by manuelbieh** [comment]
Hey. I will have to investigate a bit further. In my projects I was usually falling back to the "home" route without really having an explicit 404 page.

**Comment by manuelbieh** [comment]
Hey, I read your issue again.

Ideally you should not need to touch index.js neither in `src/client` nor in `src/server`. If you want to add custom routes you can (and should) add them to `src/shared/App.js`. This way they work on the server and on the client out of the box without any additional effort (given that you're using only components which work on both platforms).

This is the App Component in one of my last projects:

```jsx
import routes from './routes';
import Login from 'pages/Auth/Login';
import Signup from 'pages/Auth/Signup';
import PasswordReset from 'pages/Password/Reset';
import PasswordChange from 'pages/Password/Change';
import Home from 'pages/Main/Home';
import Desk from 'pages/Main/Desk';
import Garage from 'pages/Main/Garage';
import Onboarding from 'pages/Onboarding/Home';
import Error404 from 'pages/Error/404';

const App = () => (
    <Switch>
        <Route exact path={routes.main.home} component={Home} />
        <Route path={routes.main.desk.list} component={Desk} />
        <Route path={routes.auth.login} component={Login} />
        <Route path={routes.auth.signup} component={Signup} />
        <Route path={routes.password.reset} component={PasswordReset} />
        <Route path={routes.password.change} component={PasswordChange} />
        <Route path={routes.main.garage.list} component={Garage} />
        <Route path={routes.onboarding.home} component={Onboarding} />
        <Route component={Error404} />
    </Switch>
);
```

Does that solve your problem?
