### ISSUE TITLE
How can loader SCSS

### ISSUE THREAD

**Issue by tranvanthuc** [manuelbieh/react-ssr-setup#25]
I add some code below in **loaders.js** 
When I run **yarn start** it runs ok , but **yarn build**, It can't get css. Please help me. 
```
const scssLoaderServer = {
  test: /\.scss$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'css-loader/locals',
      options: {
        camelCase: true,
        importLoaders: 1,
        modules: true,
        localIdentName: '[name]__[local]--[hash:base64:5]'
      }
    },
    {
      loader: 'sass-loader',
      options: {
        sourceMap: true
      }
    }
  ]
};`

**Comment by manuelbieh** [comment]
Could you elaborate a bit on what "can't get css" exactly means? The CSS isn't generated? Do you get an error message? The server in the build mode does not automatically serve static files.

Have a look here:
https://github.com/manuelbieh/react-ssr-setup#caveats

And more specifically here:
https://github.com/manuelbieh/react-ssr-setup/blob/master/src/server/index.js#L16

Maybe that solves your problem already.

**Comment by tranvanthuc** [comment]
Thank you so much.
