### ISSUE TITLE
Assets loading

### ISSUE THREAD

**Issue by MIcQo** [manuelbieh/react-ssr-setup#36]
Hello,

I have simple question about assets loading like manifest, favicons and other stuff, how i can load it from **shared**/**assets**? The problem is that wasn't copy those files into **build** folder. 

How i can solve this little trouble? 

Thanks

**Comment by enviktorov** [comment]
Hey man, first of all thanks for this awesome boilerplate!

I also have the same problem as _MIcQo_. Assets are not transferred to build folder. Is it a bug? Or am I doing something wrong?

Thanks in advance!

**Comment by manuelbieh** [comment]
The assets need to be imported somewhere in your application as they are only copied to the build folder via file-loader:
https://github.com/manuelbieh/react-ssr-setup/blob/master/config/webpack.config.js/loaders.js#L112

Do you have a public example repository by any chance so I can have a look?
