### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by hepicek** [manuelbieh/react-ssr-setup#38]
Hi,

I tried React lazy as you recommend, but it isn't supported for server-side rendering.
Is there any workaround you know of?
Or will you change your mind to implement react loadable? They changed their license back so it should be ok.

Thanks

**Comment by Kennypt** [comment]
You can use lazy loading, but on server side you have to some something like:

`{typeof window !== 'undefined' ? (
        <Suspense fallback={<div>Loading...</div>}>
          <Footer structure={footerData} structure={footerData} />
        </Suspense>
  ) : null}`

**Comment by manuelbieh** [comment]
I'm aiming for a code base that is ready to use once official Server Side Streaming support for React has landed. This should be at some point later this year but there's still "a lot of work left" according to Sebastian Markbage ([see this thread](https://twitter.com/ManuelBieh/status/1087881021582962689)).

You could try to use [react-aldrin](https://github.com/ephem/react-aldrin) for now but I would not necessarily recommend to use it in production yet. I guess we'll have to be a bit patient for now until we can use Suspense on the server side 😕

**Comment by manuelbieh** [comment]
I'm aiming for a code base that is ready to use once official Server Side Streaming support for React has landed. This should be at some point later this year but there's still "a lot of work left" according to Sebastian Markbåge ([see this thread](https://twitter.com/ManuelBieh/status/1087881021582962689)).

You could try to use [react-aldrin](https://github.com/ephem/react-aldrin) for now but I would not necessarily recommend to use it in production yet. I guess we'll have to be a bit patient for now until we can use Suspense on the server side 😕

**Comment by manuelbieh** [comment]
Another alternative is to use the workaround @Kennypt suggested but that would mean that - depending on how high in your tree you use Suspense - you would not really have a proper server side rendering anymore.
