### ISSUE TITLE
unexpected token export lodash-es

### ISSUE THREAD

**Issue by sergeyromanovsky** [manuelbieh/react-ssr-setup#43]
Hi, I try to use your ssr setup for an existing project and i have a problem with lodash-es, which has es module import/export, and can't be compiled by server, i try to use babel/plugin-transform-modules-commonjs, and include node_modules for babel-loader, but gave no result :(, can you help me pls?

**Comment by manuelbieh** [comment]
Can you give a bit more info? Error trace, code snippets, etc?

**Comment by sergeyromanovsky** [comment]
/Users/Romanovsky/Documents/FirstBridge/searfi-front-end/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by sergeyromanovsky** [comment]
Can u pls explain, this lines `script.on('start', async () => {
        try {
            // TODO: add try/wait/retry here instead of just generally waiting for 2000 ms
            await sleep(2000);
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto(`${HOST}:${PORT}`);
            const pageContent = await page.content();
            fs.writeFileSync(`${paths.clientBuild}/index.html`, pageContent);
            await browser.close();
            script.emit('quit');
        } catch (err) {
            script.emit('quit');
            console.log(err);
        }
    });`

in srcript/build

express send html to client, we never use index.html

**Comment by manuelbieh** [comment]
First: the lodash issue should be solved with one of the recent updates. I had this error too, I don't have it anymore so I consider it done.

To your second question: it is generating an index.html file that can be used for client side rendering. Since I've introduced `--client-only` as a flag which uses HTMLWebpackPlugin for generating the HTML, this is probably not needed anymore. I will have a look at it!
