### ISSUE TITLE
express.static on both ports

### ISSUE THREAD

**Issue by ghost** [manuelbieh/react-ssr-setup#44]
Hi, again. Could you please explain why you serve a client bundle on both 8500(in src/server/index.js) and 8501(scripts/start.js) ports if you use only that served client bundle which is on host 8501. You setup HMR for the client bundle on 8501 and you link styles and scripts to HTML response which are on 8501 host too. But you do nothing with the served client bundle which is on host 8500. Thank you.

here
https://github.com/manuelbieh/react-ssr-setup/blob/master/src/server/index.js#L20
and here
https://github.com/manuelbieh/react-ssr-setup/blob/master/scripts/start.js#L72

**Comment by manuelbieh** [comment]
The server rendering application itself runs on port 8500 (and is doing that both in production and in development). Port 8501 is only used in development mode and serves the HMR bundle.
