### ISSUE TITLE
How is the production build of an application started

### ISSUE THREAD

**Issue by ifeanyidavid** [manuelbieh/react-ssr-setup#47]
I have ran `npm run build` and the build directory was generated containing the client and server directories. Then I tried running `node build/server/server.js` and it ran the application, but without the styles loaded.

Is there a way to run the production build of the application using node rather than npm start?

**Comment by manuelbieh** [comment]
Static files are intentionally not served in the production build to encourage you to setup a proper static web server:
https://github.com/manuelbieh/react-ssr-setup/blob/master/README.md#caveats

You can still use it in production (which I would not recommend) by removing the condition here:
https://github.com/manuelbieh/react-ssr-setup/blob/master/src/server/index.js#L17
