### ISSUE TITLE
Serve for production

### ISSUE THREAD

**Issue by oltodo** [manuelbieh/react-ssr-setup#6]
Hi,

How are you supposed to serve your build for in production?
I tried something like `node dist/server/server.js` but I got troubles with assets.

Thanks for sharing your configuration.

**Comment by manuelbieh** [comment]
Hey. I'm using an nginx reverse proxy for serving assets in production which is the preferred way: http://expressjs.com/de/4x/api.html#express.static

If you don#t want to do that you can use the express.static middleware in production. Have a look at this line:
https://github.com/manuelbieh/react-ssr-setup/blob/master/src/server/index.js#L17

Remove the `if (process.env.NODE_ENV === 'development')` check and you should be fine.

**Comment by oltodo** [comment]
Thanks @manuelbieh for your fast response!

**Comment by manuelbieh** [comment]
I'm not sure if you understand what you mean exactly. Could you try to explain what you mean by "compiling each time you want a production environment"?

How do you want to compile the production build? What do you mean?

You can create a build and deploy it where ever you want (the content inside of the `build/` folder). What else do you want/need?

**Comment by avinashjoshi** [comment]
I have had a similar requirement, basically just to see how things "might" potentially work on a production env. I create a `start-production.js` script. I use the port 2998 to serve static content. Of course, i built this in a hurry, and could be improved:

```
const express = require('express');
const { build } = require('./build');
const nodemon = require('nodemon');
const paths = require('../config/paths');
const { logMessage } = require('./utils');
const rimraf = require('rimraf');

const app = express();

const PRODUCTION_STATIC_PORT =
    process.env.PRODUCTION_STATIC_PORT ||
    (!isNaN(Number(process.env.PORT)) ? Number(process.env.PORT) - 2 : 2998);

const startProduction = async () => {
    const startStatic = process.env.PRODUCTION_OUTPUT_PUBLIC_PATH !== undefined;
    if (startStatic) {
        process.env.PRODUCTION_OUTPUT_PUBLIC_PATH = `http://localhost:${PRODUCTION_STATIC_PORT}/`;
    } else {
        logMessage(
            'PRODUCTION_OUTPUT_PUBLIC_PATH is not set - will not be hosting static file sever.',
            'error'
        );
    }

    await build();

    if (startStatic) {
        app.use('/', express.static(`${paths.clientBuild}/${paths.publicPath}`));
        await app.listen(PRODUCTION_STATIC_PORT);
    }

    nodemon({
        script: `${paths.serverBuild}/server.js`,
        ignore: ['src', 'scripts', 'config', './*.*', 'build/client'],
    });
};

process.on('SIGINT', () => {
    logMessage('Interrupt signal caught - Cleaning up build...');
    rimraf.sync(paths.clientBuild);
    rimraf.sync(paths.serverBuild);
    process.exit();
});

startProduction();

```

My `package.json` script has the line:
```
"start:production": "cross-env NODE_ENV=production node scripts/start-production.js",
```

Hope this helps.

**Comment by manuelbieh** [comment]
Nice! If you only need to check the client side build the easiest way to do that is probably

```
npx http-server build/client
```

That starts a static http server and serves your app on localhost:8080.

Does **not** start the server side version though.
