### ISSUE TITLE
Question: res.locals

### ISSUE THREAD

**Issue by kahurangitama** [manuelbieh/react-ssr-setup#63]
Hi! First of all I would thank you for this project, its truly awesome!
Recently I moved to @loadable/component + ssr. But still can't understand one thing in your code:
https://github.com/manuelbieh/react-ssr-setup/blob/e132ac948ab97c38395998bf72acf4a7adc7e57c/src/server/middleware/serverRenderer.tsx#L31

There is ```res.locals.assetPath``` function there. But I can't realize where it appear from? If I do console.log I'll get another functions which I suggest related to chunk extractor or something like that. But I wan't keep my res.locals clean. How can I remove it?
```
{
user: null // passportjs
store: {...}, // it's store
history: {...}, // it's history
...
// where next func came from?
  getSources: [Function: getSources],
  getStylesheetSources: [Function: getStylesheetSources],
  getStylesheets: [Function: getStylesheets],
  getJavascriptSources: [Function: getJavascriptSources],
  getJavascripts: [Function: getJavascripts],
  getImageSources: [Function: getImageSources],
  getImages: [Function: getImages],
  getManifest: [Function: getManifest],
  assetPath: [Function: assetPath],
  imageTag: [Function: imageTag],
  javascriptTag: [Function: javascriptTag],
  stylesheetTag: [Function: stylesheetTag] }
```
Search trough project didn't found anything

**Comment by manuelbieh** [comment]
It’s coming from this plugin/middleware:
https://github.com/danethurber/express-manifest-helpers/blob/master/README.md#helpers

It’s reading the manifest file created by webpack-manifest-plugin in config/webpack.config.js/plugins.js

**Comment by manuelbieh** [comment]
Used here:
https://github.com/manuelbieh/react-ssr-setup/blob/e132ac948ab97c38395998bf72acf4a7adc7e57c/src/server/index.ts#L46

**Comment by kahurangitama** [comment]
Thank you for response! I asked because suddenly assetPath() started to return an empty string and I trying to figure out what I did wrong. Thanks again!

**Comment by manuelbieh** [comment]
That sometimes happens if there were problems writing the manifest.json. It usually helps to restart the `yarn start` process.
