### ISSUE TITLE
Question: Dockerize

### ISSUE THREAD

**Issue by ppvolto** [manuelbieh/react-ssr-setup#71]
I currently try to Dockerize my Project on this Template with the help of a Container as a Builder
But the Building is not working correctly in any Dockerfile variation i know.
Therefore my Question does a "Example" Dockerfile exists to Dockerize a Application based on this template?

**Comment by manuelbieh** [comment]
Hey,

thanks for your question! I have never run or built this project in a dockerized container before, so I’m afraid I can’t answer your question and also cannot provide you with a ready-to-use Docker Image. But if you you could, in turn, create a small sample repo with your dockerfile and a quick description of your problem I will gladly have a look and try to help you solve your problem.

**Comment by ppvolto** [comment]
This a Simple setup that i currently have for my Testing for the Container as a Builder Setup
https://github.com/ppvolto/react-ssr-setup-docker

As node its irrelevant if i run NODE_ENV=production node scripts/build.js or yarn build inside the as builder part

**Comment by ppvolto** [comment]
Fund a Functional Dockerfile But now i need to check how i add nginx to it.
