### ISSUE TITLE
How to pass a language variable from ssr server to client?

### ISSUE THREAD

**Issue by v1ar31** [manuelbieh/react-ssr-setup#79]
When we use the URL with the locale parameter, the locale is expected to be transmitted to the client. For example,
`http://localhost/en/my-page` -> `en` is the locale parameter
 We want to transfer the locale parameter to the client.

> i18next.init({
>     fallbackLng: 'en',  <<- we want to change this
>     fallbackNS: ['translation'],
>     resources: { ... },
> });

`i18next-express-middleware` does not work because in the react-ssr-setup we use `react-router `instead of `express-router`

**Comment by manuelbieh** [comment]
You don't have to transfer the language parameter to the client, you already have it in the client if you have it in the URL!

If the language prefix is always present in the URL you could do something like

```js
const locale = location.pathname.split('/')[1];
```

**Comment by v1ar31** [comment]
> You don't have to transfer the language parameter to the client, you already have it in the client if you have it in the URL!
> 
> If the language prefix is always present in the URL you could do something like
> 
> ```js
> const locale = location.pathname.split('/')[1];
> ```

This solution will not work for SEO.

**Comment by manuelbieh** [comment]
If you need the locale in the rendered markup, you could edit [this part](https://github.com/manuelbieh/react-ssr-setup/blob/master/src/server/middleware/serverRenderer.tsx#L27-L38) of the server renderer to something like:

```jsx
<Html [...]>
  {content}
  <script>
    window.__detectedLanguage__ = '{detectedLanguage}';
  </script>
</Html>
```

and work with `window.__detectedLanguage__` in the client. Depends on your implementation how this should be done. I'm afraid I can't help you here without knowing your implementation of the server side part.
