### ISSUE TITLE
Separate Redux from the boiler plate to add support for graphql as well

### ISSUE THREAD

**Issue by rramaa** [manuelbieh/react-ssr-setup#86]
Separate out Redux to create a pure React boilerplate for SSR. Also add option to use graphql.

**Comment by manuelbieh** [comment]
Thanks for your suggestions. I'm currently looking into ways to make the boilerplate more flexible and configurable. GraphQL support will definitely interesting then. Until then, I will stick with Redux for now 😉

**Comment by rramaa** [comment]
Do tell if you need any help with upcoming roadmap :)
