### ISSUE TITLE
Not an issue but a question, are you planning to add styled-components? Or if you have tried, if that is hard to implement?

### ISSUE THREAD

**Issue by AndriiUhryn** [manuelbieh/react-ssr-setup#94]

**Comment by manuelbieh** [comment]
It should usually be a matter of `npm install styled-components`. If not, feel free to ask again. I’m happy to assist you here.

**Comment by AndriiUhryn** [comment]
Will leave this for all.
To enable styled-components you need:
- install styled-components module
- follow this steps https://www.styled-components.com/docs/advanced#server-side-rendering
- and it should work just fine (at least it worked for me)

Fell free to contact me if anything will appear :)
